import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { createAddress, deleteAddress, getAddresses, setDefaultAddress, updateAddress } from '../controllers/addresses.js';
const router = Router();
router.use(requireAuth);
router.get('/', getAddresses);
router.post('/', createAddress);
router.patch('/:id/default', setDefaultAddress);
router.put('/:id', updateAddress);
router.delete('/:id', deleteAddress);
export default router;
